package com.example.crud.entity;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sno
     *
     * @mbggenerated
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sname
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sage
     *
     * @mbggenerated
     */
    private Integer sage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.saddress
     *
     * @mbggenerated
     */
    private String saddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.spwd
     *
     * @mbggenerated
     */
    private String spwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.sno
     *
     * @return the value of stu.sno
     *
     * @mbggenerated
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.sno
     *
     * @param sno the value for stu.sno
     *
     * @mbggenerated
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.sname
     *
     * @return the value of stu.sname
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.sname
     *
     * @param sname the value for stu.sname
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.sage
     *
     * @return the value of stu.sage
     *
     * @mbggenerated
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.sage
     *
     * @param sage the value for stu.sage
     *
     * @mbggenerated
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.saddress
     *
     * @return the value of stu.saddress
     *
     * @mbggenerated
     */
    public String getSaddress() {
        return saddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.saddress
     *
     * @param saddress the value for stu.saddress
     *
     * @mbggenerated
     */
    public void setSaddress(String saddress) {
        this.saddress = saddress == null ? null : saddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.spwd
     *
     * @return the value of stu.spwd
     *
     * @mbggenerated
     */
    public String getSpwd() {
        return spwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.spwd
     *
     * @param spwd the value for stu.spwd
     *
     * @mbggenerated
     */
    public void setSpwd(String spwd) {
        this.spwd = spwd == null ? null : spwd.trim();
    }
}